/*** Autogenerated by WIDL 10.9 from ./windows.graphics.display.interop.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_graphics_display_interop_h__
#define __windows_graphics_display_interop_h__

/* Forward declarations */

#ifndef __IDisplayInformationStaticsInterop_FWD_DEFINED__
#define __IDisplayInformationStaticsInterop_FWD_DEFINED__
typedef interface IDisplayInformationStaticsInterop IDisplayInformationStaticsInterop;
#ifdef __cplusplus
interface IDisplayInformationStaticsInterop;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <inspectable.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IDisplayInformationStaticsInterop interface
 */
#ifndef __IDisplayInformationStaticsInterop_INTERFACE_DEFINED__
#define __IDisplayInformationStaticsInterop_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDisplayInformationStaticsInterop, 0x7449121c, 0x382b, 0x4705, 0x8d,0xa7, 0xa7,0x95,0xba,0x48,0x20,0x13);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7449121c-382b-4705-8da7-a795ba482013")
IDisplayInformationStaticsInterop : public IInspectable
{
    virtual HRESULT STDMETHODCALLTYPE GetForMonitor(
        HMONITOR monitor,
        REFIID riid,
        void **displayInfo) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetForWindow(
        HWND window,
        REFIID riid,
        void **displayInfo) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDisplayInformationStaticsInterop, 0x7449121c, 0x382b, 0x4705, 0x8d,0xa7, 0xa7,0x95,0xba,0x48,0x20,0x13)
#endif
#else
typedef struct IDisplayInformationStaticsInteropVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDisplayInformationStaticsInterop *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDisplayInformationStaticsInterop *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDisplayInformationStaticsInterop *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        IDisplayInformationStaticsInterop *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        IDisplayInformationStaticsInterop *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        IDisplayInformationStaticsInterop *This,
        TrustLevel *trustLevel);

    /*** IDisplayInformationStaticsInterop methods ***/
    HRESULT (STDMETHODCALLTYPE *GetForMonitor)(
        IDisplayInformationStaticsInterop *This,
        HMONITOR monitor,
        REFIID riid,
        void **displayInfo);

    HRESULT (STDMETHODCALLTYPE *GetForWindow)(
        IDisplayInformationStaticsInterop *This,
        HWND window,
        REFIID riid,
        void **displayInfo);

    END_INTERFACE
} IDisplayInformationStaticsInteropVtbl;

interface IDisplayInformationStaticsInterop {
    CONST_VTBL IDisplayInformationStaticsInteropVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDisplayInformationStaticsInterop_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IDisplayInformationStaticsInterop_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDisplayInformationStaticsInterop_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define IDisplayInformationStaticsInterop_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define IDisplayInformationStaticsInterop_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define IDisplayInformationStaticsInterop_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IDisplayInformationStaticsInterop methods ***/
#define IDisplayInformationStaticsInterop_GetForMonitor(This,monitor,riid,displayInfo) (This)->lpVtbl->GetForMonitor(This,monitor,riid,displayInfo)
#define IDisplayInformationStaticsInterop_GetForWindow(This,window,riid,displayInfo) (This)->lpVtbl->GetForWindow(This,window,riid,displayInfo)
#else
/*** IUnknown methods ***/
static inline HRESULT IDisplayInformationStaticsInterop_QueryInterface(IDisplayInformationStaticsInterop* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IDisplayInformationStaticsInterop_AddRef(IDisplayInformationStaticsInterop* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IDisplayInformationStaticsInterop_Release(IDisplayInformationStaticsInterop* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT IDisplayInformationStaticsInterop_GetIids(IDisplayInformationStaticsInterop* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT IDisplayInformationStaticsInterop_GetRuntimeClassName(IDisplayInformationStaticsInterop* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT IDisplayInformationStaticsInterop_GetTrustLevel(IDisplayInformationStaticsInterop* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IDisplayInformationStaticsInterop methods ***/
static inline HRESULT IDisplayInformationStaticsInterop_GetForMonitor(IDisplayInformationStaticsInterop* This,HMONITOR monitor,REFIID riid,void **displayInfo) {
    return This->lpVtbl->GetForMonitor(This,monitor,riid,displayInfo);
}
static inline HRESULT IDisplayInformationStaticsInterop_GetForWindow(IDisplayInformationStaticsInterop* This,HWND window,REFIID riid,void **displayInfo) {
    return This->lpVtbl->GetForWindow(This,window,riid,displayInfo);
}
#endif
#endif

#endif


#endif  /* __IDisplayInformationStaticsInterop_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HMONITOR_UserSize     (ULONG *, ULONG, HMONITOR *);
unsigned char * __RPC_USER HMONITOR_UserMarshal  (ULONG *, unsigned char *, HMONITOR *);
unsigned char * __RPC_USER HMONITOR_UserUnmarshal(ULONG *, unsigned char *, HMONITOR *);
void            __RPC_USER HMONITOR_UserFree     (ULONG *, HMONITOR *);
ULONG           __RPC_USER HWND_UserSize     (ULONG *, ULONG, HWND *);
unsigned char * __RPC_USER HWND_UserMarshal  (ULONG *, unsigned char *, HWND *);
unsigned char * __RPC_USER HWND_UserUnmarshal(ULONG *, unsigned char *, HWND *);
void            __RPC_USER HWND_UserFree     (ULONG *, HWND *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __windows_graphics_display_interop_h__ */
